name: Notificación a ntfy

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Ejecutar programa Hola Mundo
        run: node index.js

      - name: Enviar notificación a ntfy
        run: |
          curl \
            -H "Title: Nuevo push en main" \
            -d "El usuario ${{ github.actor }} subió código a ${{ github.repository }}" \
            ntfy.sh/devops-itla
